# Generated by Django 5.2.4 on 2025-08-13 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=15)),
                ('auth_name', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='')),
                ('uname', models.CharField(max_length=10)),
                ('password', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Reject', max_length=10)),
                ('section', models.CharField(choices=[('Road', 'Road'), ('Buildings', 'Buildings'), ('Bridges', 'Bridges'), ('Signboard', 'Signboard'), ('Others', 'Others')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=15)),
                ('Username', models.CharField(max_length=15)),
                ('Password', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('district', models.CharField(max_length=20)),
                ('taluk', models.CharField(max_length=20)),
                ('panchayat', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Reject', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('application_fee', models.IntegerField(default=0)),
                ('authority_response', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.auth_reg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('progress_percent', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='progress/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.complaint')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.auth_reg')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user_reg')),
            ],
        ),
    ]
