# Generated by Django 5.2.4 on 2025-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_auth_reg_status_alter_user_reg_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_reg',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
